services:
  worker:
    build:
      context: .
      dockerfile: infra/worker/Dockerfile
    container_name: mdb_sync_worker
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    networks:
      - db_network
    restart: always

networks:
  db_network:
    external: true
    name: db_default
